FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

COPY src/ ./

RUN mkdir -p /root/.nuget/NuGet
COPY ./config/NuGetPackageSource.Config /root/.nuget/NuGet/NuGet.Config

RUN dotnet build EventWorkerHost/EventWorkerHost.csproj -o event-worker

FROM build AS publish
WORKDIR /app

RUN dotnet publish -c Release -o dist/event-worker EventWorkerHost/EventWorkerHost.csproj

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

COPY --from=publish /app/dist ./

EXPOSE 80

ENV ASPNETCORE_ENVIRONMENT Docker

ENTRYPOINT ["dotnet", "event-worker/MontyHallProblemSimulation.ReadSide.EventWorkerHost.dll"]