// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MontyHallProblemSimulation.Infrastructure.Simulation.Cqrs.Repository.Sqlite;

namespace MontyHallProblemSimulation.Infrastructure.Simulation.Cqrs.Repository.Sqlite.Migrations
{
    [DbContext(typeof(SimulationAggregateRootDbContext))]
    partial class SimulationAggregateRootDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("MontyHallProblemSimulation.Domain.SimulationAggregateRoot.SimulationAggregateRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("DoorChanged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DoorChanged");

                    b.Property<long>("FailCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FailCount");

                    b.Property<bool>("IsMarkedToDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsMarkedToDelete");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUpdatedBy");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<long>("NumberOfSimulations")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberOfSimulations");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SuccessCount");

                    b.Property<double>("SuccessRatio")
                        .HasColumnType("REAL")
                        .HasColumnName("SuccessRatio");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("SimulationAggregateRoots");
                });
#pragma warning restore 612, 618
        }
    }
}
